# Generated by Django 5.0.4 on 2024-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("compleated", "Compleated"),
                    ("canceled", "Canceled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
