# Generated by Django 5.0.4 on 2024-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="items",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
